#!/bin/bash

actual=`cat /sys/class/backlight/intel_backlight/actual_brightness`
max=`cat /sys/class/backlight/intel_backlight/max_brightness`

if (($# == 0))
  then
    echo $actual
elif [ $1 == - ]
  then
	  modified=$((actual / 2))
    sudo su -c "cat > /sys/class/backlight/intel_backlight/brightness << EOF
$modified
EOF"
elif [ $1 == + ]
  then
	  modified=$((actual * 2))
    if ((modified < max))
      then
        sudo su -c "cat > /sys/class/backlight/intel_backlight/brightness << EOF
$modified
EOF"
    else
      echo "This is the maximum brightness."
    fi
else
  echo "Error: Unsupported argument."
fi
